github: [Asilbek2706] # Agar GitHub Sponsors'da ro'yxatdan o'tgan bo'lsangiz
patreon: asilbek_karomatov # Patreon loginigiz
ko_fi: asilbek2706 # Ko-fi loginigiz
custom: ["https://www.buymeacoffee.com/asilbek"] # Boshqa istalgan havola
